title = "Byteparse"
gitRepoUrl = "https://github.com/plainenglishh/byteparse"
gitSourceBranch = "main"
changelog = true
classOrder = []

[docusaurus]
tagline = "Library for serialising and deserialising binary formats"
titleDelimiter = "•"
organizationName = "plainenglishh"
projectName = "byteparse"

[home]
enabled = true
includeReadme = true

[[navbar.items]]
href = "https://github.com/plainenglishh/byteparse/releases"
label = "Releases"
position = "right"

[footer]
style = "dark"
copyright = "Copyright plainenglish © 2025. Built with Moonwave and Docusaurus"

