title = "Byteparse"
gitRepoUrl = "https://github.com/plainenglishh/byteparse"

gitSourceBranch = "main"
changelog = true
classOrder = []

[footer]
style = "dark"
copyright = "Copyright plainenglish © 2025. Built with Moonwave and Docusaurus"

[docusaurus]
url = "https://byteparse.plainenglish.xyz"
baseUrl = "/"