on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    test:
        name: test
        runs-on: ubuntu-latest
        steps:
            - uses: CompeyDev/setup-rokit@v0.1.2
            - name: Test
              run: lune run scripts/test
