on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    test:
        name: Test & Bench
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: CompeyDev/setup-rokit@v0.1.2
            - name: Test
              run: lune run scripts/test
            - name: Benchmark
              run: lune run scripts/bench